const phone = '529381698818';
const toWhatsApp = message => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
document.querySelectorAll('[data-whatsapp]').forEach(link => { link.href = toWhatsApp(link.dataset.whatsapp); link.target = '_blank'; link.rel = 'noopener'; });
const menuButton = document.querySelector('.menu-toggle'), nav = document.querySelector('.site-nav');
menuButton.addEventListener('click', () => { const open = menuButton.getAttribute('aria-expanded') === 'true'; menuButton.setAttribute('aria-expanded', String(!open)); nav.classList.toggle('open', !open); });
nav.querySelectorAll('a').forEach(link => link.addEventListener('click', () => { menuButton.setAttribute('aria-expanded', 'false'); nav.classList.remove('open'); }));
const featured = products.filter(product => product.featured);
const productCard = product => `<article class="product-card"><img src="${product.image}" alt="${product.name}"><div><small>${product.line}</small><h3>${product.name}</h3><p>${product.short}</p><a href="catalogo.html?product=${product.id}">Ver producto <b>→</b></a></div></article>`;
document.querySelector('#featured-grid').innerHTML = featured.map(productCard).join('');
const routes = { digestión: ['dtx-oxigen','mybio-nco','begreen'], energía: ['dtx-oxigen','my-suker-caps','mybio-nco'], descanso: ['mahal-gel','mybio-nco'], piel: ['serum-vitamina-c'], rutina: ['dtx-oxigen','mahal-gel','ftx-plus'] };
const dialog = document.querySelector('#recommendation');
document.querySelectorAll('[data-need]').forEach(button => button.addEventListener('click', () => { const list = routes[button.dataset.need].map(id => products.find(product => product.id === id)).filter(Boolean); document.querySelector('#dialog-title').textContent = button.textContent.replace(/^\s*\d+\s*/, '').replace('→', '').trim(); document.querySelector('#dialog-products').innerHTML = list.map(product => `<a href="catalogo.html?product=${product.id}"><img src="${product.image}" alt=""><span><b>${product.name}</b><small>${product.short}</small></span><i>→</i></a>`).join(''); dialog.showModal(); }));
document.querySelector('.dialog-close').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); });
