const phone = '529381698818';
const search = document.querySelector('#search'), filters = document.querySelector('#filters'), grid = document.querySelector('#catalog-grid'), count = document.querySelector('#count'), dialog = document.querySelector('#product-dialog');
const lines = ['Todo', ...new Set(products.map(product => product.line))]; let activeLine = new URLSearchParams(location.search).get('line') || 'Todo'; let term = '';
filters.innerHTML = lines.map(line => `<button class="${line === activeLine ? 'active' : ''}" data-line="${line}">${line}</button>`).join('');
const item = product => `<article class="catalog-card"><img src="${product.image}" alt="${product.name}"><div><small>${product.line}</small><h2>${product.name}</h2><p>${product.short}</p><button data-product="${product.id}">Ver detalles <b>→</b></button></div></article>`;
function render(){const list=products.filter(p=>(activeLine==='Todo'||p.line===activeLine)&&`${p.name} ${p.line}`.toLowerCase().includes(term));grid.innerHTML=list.map(item).join('')||'<p class="empty">No encontramos un producto con esa búsqueda.</p>';count.textContent=`${list.length} ${list.length===1?'producto':'productos'} disponibles para consultar`;document.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>openProduct(button.dataset.product)));}
filters.addEventListener('click',event=>{if(!event.target.matches('button'))return;activeLine=event.target.dataset.line;filters.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.line===activeLine));render();});search.addEventListener('input',()=>{term=search.value.toLowerCase().trim();render();});
function openProduct(id){const product=products.find(p=>p.id===id);document.querySelector('#product-detail').innerHTML=`<img src="${product.image}" alt="${product.name}"><p class="eyebrow">${product.line}</p><h2>${product.name}</h2><p>${product.short}</p><dl><div><dt>Presentación</dt><dd>${product.presentation}</dd></div><div><dt>Disponibilidad y precio</dt><dd>Consulta con Erika</dd></div></dl><a class="button button-dark" href="https://wa.me/${phone}?text=${encodeURIComponent(`Hola Erika, vi ${product.name} en Luces Brillantes y quiero recibir información.`)}" target="_blank" rel="noopener">Consultar con Erika</a>`;dialog.showModal();}
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});render();
