window.LB_PRODUCTS = [
{"id":"ftx-plus","name":"FTX Plus","line":"Bienestar","image":"assets/products/ftx-plus.webp","description":"Suplemento alimenticio en tableta a base de cartílago de tiburón, encino y guásimo.","presentation":"30 tabletas","code":"PT748","ingredients":"Estearato de magnesio, vitamina C, potasio, vitamina E, calcio de coral, vitamina D3, cartílago de tiburón, encino, sauce blanco y guásimo.","usage":"Tomar una tableta al día.","tags":["rodillas y articulaciones","rutina y ejercicio","bienestar"],"featured":true,"bestSeller":true},
{"id":"dtx-oxigen-liquido","name":"FT-Elym DTX Oxigen","line":"FT-Elym","image":"assets/products/dtx-oxigen-liquido.webp","description":"Suplemento alimenticio líquido a base de alga espirulina, alfalfa y apio.","presentation":"500 ml / 1 L","code":"PT725 / PT774","ingredients":"Calcio de coral, vitamina C, stevia, alga espirulina, alfalfa, piña, perejil, té verde, menta, apio y clorofila.","usage":"Diluir 15 ml en 250 ml de agua fría y tomar antes de la comida.","tags":["digestión","bienestar general","energía y vitalidad"],"featured":true,"bestSeller":true},
{"id":"my-suker-caps","name":"My Suker Caps","line":"Bienestar","image":"assets/products/suker-juice.webp","description":"Suplemento alimenticio en cápsula a base de plantas e ingredientes indicados en el catálogo.","presentation":"60 cápsulas","code":"PT743","ingredients":"Guayacán amarillo, guaraná, estearato de magnesio, perejil, xoconostle, neem, palo de arco y matarique.","usage":"Tomar una cápsula después del desayuno.","tags":["bienestar general"],"featured":true,"bestSeller":true},
{"id":"my-sir-q-caps","name":"My Sir-Q Caps","line":"Bienestar","image":"assets/products/my-sir-q-caps.webp","description":"Suplemento alimenticio en cápsula a base de cola de caballo, semilla de chía y semilla de uva.","presentation":"60 cápsulas","code":"PT759","ingredients":"Limón, semilla de chía, rusco, semilla de uva, lecitina de soya, cola de caballo, hamamelis y chaya.","usage":"Tomar una cápsula por la mañana y otra por la noche.","tags":["bienestar general"],"featured":true,"bestSeller":true},
{"id":"begreen","name":"BeGreen","line":"Bienestar","image":"assets/products/begreen.webp","description":"Suplemento alimenticio líquido a base de alga espirulina, clorofila y hierbabuena.","presentation":"500 ml / 1 L","code":"PT747 / PT746","ingredients":"Alga espirulina, té verde, alfalfa, hierbabuena, menta, clorofila, estevia y vitamina C.","usage":"Diluir 15 ml en 250 ml de agua y tomar antes del desayuno.","tags":["digestión","bienestar general"],"featured":true,"bestSeller":true},
{"id":"mybio-nco","name":"MyBio-Nco","line":"Bienestar","image":"assets/products/mybio-nco.webp","description":"Producto de la línea Bienestar. Consulta con Erika la información y recomendación correspondiente.","presentation":"Consultar","code":"","ingredients":"El catálogo incluye ingredientes como maltodextrina, estevia, moringa y uña de gato.","usage":"Consulta la indicación del producto y con Erika antes de utilizarlo.","tags":["bienestar general","selecciones"],"featured":true,"bestSeller":true},
{"id":"mahal","name":"Mahal","line":"Bienestar","image":"assets/products/mahal-gel.webp","description":"Familia de productos Mahal. En el catálogo aparecen opciones como Mahal Gel Corporal Relajante y My Mahal Caps.","presentation":"Varias presentaciones","code":"","ingredients":"Depende de la presentación.","usage":"Depende de la presentación.","tags":["descanso","rodillas y articulaciones","bienestar"],"featured":true,"bestSeller":true},
{"id":"ag-coloidal","name":"Ag Coloidal","line":"Avancely","image":"assets/products/ag-coloidal.webp","description":"Producto de la línea Avancely a base de agua destilada y nanopartículas de plata coloidal.","presentation":"Consultar disponibilidad","code":"","ingredients":"Agua destilada y nanopartículas de plata coloidal de 1 a 10 nanómetros con iones de plata (20 ppm).","usage":"Consultar la indicación del catálogo y con Erika.","tags":["cuidado de la piel","bienestar general"],"featured":true,"bestSeller":true},
{"id":"my-belly-t","name":"My Belly-t","line":"Bienestar","image":"assets/products/my-belly-t.webp","description":"Suplemento alimenticio en polvo a base de colágeno hidrolizado y ácido hialurónico.","presentation":"350 g","code":"PT783 / PT754","ingredients":"Extracto de naranja / uva, colágeno hidrolizado, Omega 3,6,9, calcio, magnesio, potasio, vitaminas A, C y E, ácido hialurónico, hierro, zinc y biotina.","usage":"Disolver 8 g en 250 ml de agua y tomar por la mañana.","tags":["rodillas y articulaciones","cuidado de la piel","bienestar general"],"featured":true},
{"id":"revenue-juice","name":"Revenue Juice","line":"Bienestar","image":"assets/products/revenue-juice.webp","description":"Suplemento alimenticio líquido a base de goji, mangostán y guaraná.","presentation":"1 L","code":"PT733","ingredients":"Goji, mangostán, guaraná, noni, té verde, arándano, tamarindo, guayaba, mango, semilla de uva y vitaminas.","usage":"Disolver 20 ml en 250 ml de agua antes del desayuno.","tags":["energía y vitalidad","nutrición","selecciones"],"featured":true},
{"id":"my-revenue-shake","name":"My Revenue Shake","line":"Bienestar","image":"assets/products/my-revenue-shake.webp","description":"Suplemento alimenticio en polvo a base de proteína aislada de chícharo, avena y cocoa.","presentation":"500 g","code":"PT734","ingredients":"Proteína aislada de chícharo, leche de coco, avena, cocoa, colágeno hidrolizado, noni y vitaminas.","usage":"Disolver 8 g en 250 ml de agua con hielos y tomar por la mañana.","tags":["nutrición","rutina y ejercicio","selecciones"],"featured":true},
{"id":"my-revenue-caps","name":"My Revenue Caps","line":"Bienestar","image":"assets/products/my-revenue-caps.webp","description":"Suplemento alimenticio en cápsula a base de granada, acaí y noni.","presentation":"60 cápsulas","code":"PT735","ingredients":"Vitaminas B1, B6, B2, A, ácido fólico, B12, C, granada, acaí, noni, guanábana, guaraná, mangostán y goji.","usage":"Tomar una cápsula al día.","tags":["energía y vitalidad","bienestar general"],"featured":true},
{"id":"mymahal-ex","name":"MyMahal-Ex","line":"Bienestar","image":"assets/products/mymahal-ex.webp","description":"Suplemento alimenticio líquido a base de pasiflora, cedrón y flor de manita.","presentation":"500 ml","code":"PT752","ingredients":"Vitaminas, cedrón, pasiflora, flor de manita, ácido glutámico y L-glutatión.","usage":"Diluir 20 ml en 250 ml de agua 2 veces al día.","tags":["descanso","bienestar general"],"featured":true},
{"id":"mahal-gel","name":"Mahal Gel Corporal Relajante","line":"Bienestar","image":"assets/products/mahal-gel.webp","description":"Gel corporal para masaje. El catálogo lo menciona para espalda, pies y rodillas antes y después del ejercicio.","presentation":"300 g","code":"PT772","ingredients":"Pirul, romero, albahaca, árnica, eucalipto, salvia y aceites esenciales, entre otros.","usage":"Aplicar directamente en el área a tratar en forma de masaje suave.","tags":["rodillas y articulaciones","rutina y ejercicio"],"featured":true},
{"id":"dtx-oxigen-polvo","name":"FT-Elym DTX Oxigen","line":"FT-Elym","image":"assets/products/dtx-oxigen-polvo.webp","description":"Presentación en polvo de DTX Oxigen.","presentation":"Consultar presentación","code":"","ingredients":"Alga espirulina, alfalfa y apio, entre otros ingredientes indicados en el catálogo.","usage":"Consultar la indicación correspondiente.","tags":["digestión","bienestar general"],"featured":false},
{"id":"suker-juice","name":"Suker Juice","line":"Bienestar","image":"assets/products/suker-juice.webp","description":"Suplemento alimenticio líquido a base de yaca, guaraná y xoconostle.","presentation":"500 ml","code":"PT744","ingredients":"Guayacán amarillo, guaraná y otros ingredientes indicados en el catálogo.","usage":"Consultar la indicación del catálogo y con Erika.","tags":["selecciones","bienestar general"],"featured":false}
];
